protocol lda {
	mail_plugins {
		sieve = yes
	}
}

protocol lmtp {
	mail_plugins {
		sieve = yes
	}
}

mailbox Junk {
	sieve_script report-spam {
		type = before
		cause = copy
		path = /srv/mail/sieve/global/rspamd-learn-spam.sieve
	}
}

imapsieve_from Junk {
	sieve_script report-ham {
		type = before
		cause = copy
		path = /srv/mail/sieve/global/rspamd-learn-ham.sieve
	}
}
