#!/bin/sh
# Syntax: password user@domain new-password
[ "$#" = 2 ] || exit 1
echo $1 |grep -q @ || exit 2
. /usr/libexec/vmail/mail.common

E="$1"
U="`echo $1 |cut -d@ -f1`"
D="`echo $1 |cut -d@ -f2`"
P="{sha256}`echo -n $2 |openssl dgst -sha256 -binary |openssl enc -base64`"

echo "UPDATE users SET c_password='$P' WHERE c_uid='$E';" |$DB_CMD

. /usr/libexec/vmail/mail.cleanup
